In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element
a[0,4]

5

In [ ]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:,6]

array([ 7, 14])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,0:7:2]

array([1, 3, 5, 7])

In [ ]:
a[1,5]= 20
print(a)

a[:,2]= [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3-D Example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
b[0,0,:] = [9,8]
print(b)

[[[9 8]
  [3 4]]

 [[5 6]
  [7 8]]]
