In [1]:
# About Mathematics
import numpy as np


In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a + 2

array([3, 4, 5])

In [6]:
a - 2

array([-1,  0,  1])

In [7]:
a*3

array([3, 6, 9])

In [8]:
a/2

array([0.5, 1. , 1.5])

In [9]:
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [10]:
a**2

array([1, 4, 9])

In [11]:
# Take sin of all the values
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [12]:
# Take cos of all the values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [15]:
# Linear Algebra
# We do matrix multiplication here

c = np.full((2,3),2)
print(c)

d = np.ones((3,2))
print(d)

np.matmul(c,d)

[[2 2 2]
 [2 2 2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[6., 6.],
       [6., 6.]])

In [19]:
# Determinant of matrix
e = np.identity(3)

np.linalg.det(e)

1.0

In [20]:
# Statistics

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.min(stats,axis=1)
# It gives min value at first row, second row and so on
# Here min value at first row is 1 and that of at second row is 4

array([1, 4])

In [25]:
np.min(stats)
# It gives minumum value from whole matrix.

1

In [27]:
np.max(stats)
# It gives maximum value from whole matrix.

6

In [28]:
np.max(stats,axis = 1)
# It gives maximum value at first row, second row and so on.
# Here max value at first row is 3 and that of at second row is 6

array([3, 6])

In [34]:
# Reorganizing arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((2,4))
print(after)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [37]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
# Horizontally stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [44]:
# Import necessary libraries
from google.colab import files
import numpy as np

# Upload the file
uploaded = files.upload()

Saving data.txt to data.txt


In [47]:
# Load data from file

filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata



array([[ 5,  4,  3,  2,  1,  0],
       [18, 19, 20, 21, 22, 23],
       [44, 24, 29, 22, 23, 25],
       [99, 88, 77, 66, 55, 33]], dtype=int32)

In [48]:
# Boolean Masking and Advanced Indexing

filedata > 50



array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True, False]])

In [49]:
filedata[filedata > 50]

array([99, 88, 77, 66, 55], dtype=int32)

In [50]:
# You can index with a list in NUmPY

abc = np.array([1,2,3,4,5,6,7,8,9])
abc[[1,2,8]]

array([2, 3, 9])

In [57]:
np.any(filedata > 50, axis = 0)

array([ True,  True,  True,  True,  True, False])

In [60]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False,  True]])