In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype= 'int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print(b)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


In [ ]:
# Get Dimention
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# Get Shape
a.shape

(3,)

In [ ]:
# Get Shape
b.shape

(3, 3)

In [ ]:
# Get type
a.dtype

dtype('int16')

In [ ]:
# Get type
b.dtype

dtype('float64')

In [ ]:
# Get size
a.itemsize

4

In [ ]:
# Get total size
b.size * b.itemsize

72

In [ ]:
# Get total size
b.nbytes

72