In [2]:
import numpy as np

In [16]:
## All 0s martix
np.zeros((5,3,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [19]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [22]:
# Any other number
np.full((2,3),99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [25]:
# Any other number (full_like)

a = np.array([1,2,3]),([4,5,6])
np.full_like(a,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [27]:
# Random decimal numbers between 0s and 1s
np.random.rand(4,2,3)

array([[[0.69919291, 0.37624284, 0.55618858],
        [0.07373758, 0.80800125, 0.74655161]],

       [[0.95248921, 0.45238371, 0.05237075],
        [0.18812187, 0.51022578, 0.72353087]],

       [[0.73993579, 0.22671643, 0.0294416 ],
        [0.39196203, 0.36838151, 0.95087934]],

       [[0.35402051, 0.09585572, 0.38585731],
        [0.3494319 , 0.24924895, 0.02552309]]])

In [37]:
# Random Integer Values

np.random.randint(-4,9,size=(3,3))

array([[-3,  5,  2],
       [ 7,  5,  4],
       [ 5, -4,  6]])

In [39]:
# Identity Matirx

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
# Repeating the matrix

arr= np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
# Things we should notice while copying one array to another array

c = np.array([1,2,3])
d = c.copy()
d[0] = 100

print(d)
print(c)

[100   2   3]
[1 2 3]
